name: Build Android APK

on:
  push:
    branches:
      - main  # You can replace "main" with your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Set up Gradle
      - name: Set up Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.2-bin.zip
          unzip gradle-7.2-bin.zip
          export PATH=$PWD/gradle-7.2/bin:$PATH

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease
